apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flowmaestro-staging

bases:
  - ../../base

commonLabels:
  environment: staging

# Namespace override
namespace: flowmaestro-staging

# Patches for staging-specific configuration
patchesStrategicMerge:
  - replica-patch.yaml
  - resource-patch.yaml
  - gcs-configmap-patch.yaml

# Image overrides
images:
  - name: us-central1-docker.pkg.dev/flowmaestro-prod/flowmaestro/backend
    newTag: staging
  - name: us-central1-docker.pkg.dev/flowmaestro-prod/flowmaestro/frontend
    newTag: staging
  - name: us-central1-docker.pkg.dev/flowmaestro-prod/flowmaestro/marketing
    newTag: staging
  - name: us-central1-docker.pkg.dev/flowmaestro-prod/flowmaestro/static
    newTag: staging
